### ISSUE TITLE
list forum discus

### ISSUE THREAD

**Issue by Azhura-DH** [SMKN-8-Malang-SMK-CODING/Budayaku#4]
list forum discus tidak langsung terhubung apabila user mengupdate profile

`override fun onBindViewHolder(holder: Holder, position: Int) {
        firestore.collection("users").document(**list[position]._user_id_**).get()
            .addOnSuccessListener {
                val user: User = it.toObject()!!

                holder.itemView.tv_forumUsername.text = user.username
                Glide.with(context).load(user.user_avatar)
                    .apply(RequestOptions())
                    .into(holder.itemView.civ_user)
            }.addOnFailureListener {
                Toast.makeText(context, it.toString(), Toast.LENGTH_SHORT).show()
            }
}`

> please help me solve this problem T_T

**Comment by tioirawan** [comment]
nope

**Comment by tioirawan** [comment]
Masalahnya bukan di scriptnya, tapi di firestorenya, di collection forum, beberapa data tidak terdapat user id

**Comment by Azhura-DH** [comment]
oh jadi harus semuanya punya user_id ?

**Comment by tioirawan** [comment]
iya, karena firebase collection document tidak memanggil onErrorListener jika parameter di method document tidak terpenuhi
